version: '3'

services:
  site:
    image: site:latest
    network_mode: host
    ports:
      - "80:8080"
      - "1234:1234"
    volumes:
      - ../.zsh_history:/root/.zsh_history
    ulimits:
      nofile:
        soft: 999999
        hard: 999999
    command: ["pm2-runtime", "start", "ecosystem.config.js", "--only", "site"]

  redis:
    image: redis:latest
    network_mode: host
    volumes:
      - ../.redis:/data

  node:
    image: arrow-testnet:latest
    ports:
      - "18232:18232"
      - "17654:17654"
    volumes:
      - ../.arrow-data:/root/.arrow

# vim:set ts=2 sw=2 smarttab:
